// <auto-generated />
using MVCApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCApp.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220926134005_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCApp.Models.Golongan", b =>
                {
                    b.Property<int>("IdGolongan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaGolongan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGolongan");

                    b.ToTable("Golongans");
                });

            modelBuilder.Entity("MVCApp.Models.Pegawai", b =>
                {
                    b.Property<int>("idPegawai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("golonganPegawai")
                        .HasColumnType("int");

                    b.Property<string>("jabatanPegawai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("namePegawai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nipPegawai")
                        .HasColumnType("int");

                    b.HasKey("idPegawai");

                    b.ToTable("Pegawaii");
                });
#pragma warning restore 612, 618
        }
    }
}
