// <auto-generated />
using MVCApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCApp.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220927025542_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCApp.Models.Golongan", b =>
                {
                    b.Property<int>("IdGolongan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaGolongan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGolongan");

                    b.ToTable("Golongans");
                });

            modelBuilder.Entity("MVCApp.Models.Pegawai", b =>
                {
                    b.Property<int>("idPegawai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGolongan")
                        .HasColumnType("int");

                    b.Property<string>("jabatanPegawai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("namePegawai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nipPegawai")
                        .HasColumnType("int");

                    b.HasKey("idPegawai");

                    b.HasIndex("IdGolongan");

                    b.ToTable("Pegawaii");
                });

            modelBuilder.Entity("MVCApp.Models.Representasi", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("dalamkota")
                        .HasColumnType("int");

                    b.Property<int>("luarkota")
                        .HasColumnType("int");

                    b.Property<string>("uraian")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Represtasis");
                });

            modelBuilder.Entity("MVCApp.Models.TiketPesawat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("harga")
                        .HasColumnType("int");

                    b.Property<string>("ruteAwal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ruteTujuan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TiketPesawat");
                });

            modelBuilder.Entity("MVCApp.Models.UangHarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("dalamkota")
                        .HasColumnType("int");

                    b.Property<int>("diklat")
                        .HasColumnType("int");

                    b.Property<int>("luarkota")
                        .HasColumnType("int");

                    b.Property<string>("provinsi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UangHarian");
                });

            modelBuilder.Entity("MVCApp.Models.Pegawai", b =>
                {
                    b.HasOne("MVCApp.Models.Golongan", "Golongan")
                        .WithMany()
                        .HasForeignKey("IdGolongan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
